apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USERNAME: "userkube"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # (opcional) gestiona tus secretos de app aquí
  API_KEY: "REEMPLAZA_CON_TU_API_KEY"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      imagePullSecrets:
        - name: nexus-docker   # el Jenkinsfile lo crea/actualiza antes del apply
      containers:
        - name: backend-test
          # Imagen base; luego el pipeline la fuerza a :${BUILD_NUMBER}
          image: host.docker.internal:8082/backend-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERNAME
            # - name: API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: app-secrets
            #       key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: backend-test
spec:
  type: ClusterIP
  selector:
    app: backend-test
  ports:
    - name: http
      port: 80
      targetPort: 3000
