version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - devnet

  jenkins:
    build:
      context: ./jenkins     # Ajusta si tu Dockerfile está en otra carpeta
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home   # Datos persistentes
      - /var/run/docker.sock:/var/run/docker.sock  # Permite a Jenkins usar Docker del host
    networks:
      - devnet

  nexus:
    image: sonatype/nexus3
    container_name: nexus_repo
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - devnet

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "8084:9000"
    depends_on:
      - db_sonar
    networks:
      - devnet

  db_sonar:
    image: postgres:15
    container_name: db_sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  jenkins_home:
  nexus-data:
  postgresql:
